version: '3.8'
services:
  hotel_app:
    image: 'springappimage'
    build:
      context: .
    container_name: hotel_app
    depends_on:
      - hoteldb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hoteldb:5432/hotelbase
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9090:9090"


  hoteldb:
    image: postgresimg
    container_name: hoteldb
    environment:
     - POSTGRES_DB hotelbase
     - POSTGRES_USER ${POSTGRES_USER}
     - POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
