apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  application.properties:
   spring.datasource.url=jdbc:postgresql://hoteldb:2345/hotelbase
   spring.datasource.username=postgres
   spring.datasource.password=n11


---
apiVersion: v1
kind: Secret
metadata:
  name: project-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: bjEx=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: natalija111/springappimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: password
