apiVersion: v1
kind: Service
metadata:
  name: hotelapp-service
  namespace: hotels-namespace
spec:
  selector:
    app: hotel-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
