name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up PostgreSQL
      uses: postgres/actions/setup@v2
      with:
       
        postgresql-db: hotelbase
        postgresql-user:  ${{ secrets.POSTGRES_USERNAME}}
        postgresql-password: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Run integration tests
      run: mvn verify -Pintegration
    
    - name: Build and push DockerFile
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app1:latest
